openapi: 3.0.0
info:
  title: "Flasking Around API"
  description: "Some sort of API for cool stuff yay"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Transaction:
      type: "object"
      required:
        - date
        - desc
        - cost
        - balance
      properties:
        date:
          type: "string"
        desc:
          type: "string"
        cost:
          type: "string"
        balance:
          type: "string"
    Account:
      type: "object"
      required:
        - nickname
        - bank_name
        - account_type
      properties:
        nickname:
          type: "string"
        bank_name:
          type: "string"
        account_type:
          type: "string"
    Account_List:
      type: "array"

  parameters:
    id:
      name: "id"
      description: "The id is the hashed transaction"
      in: path
      required: True
      schema:
        type: string
    desc:
      name: "desc"
      description: "the description of a transaction"
      in: query 
      required: True
      schema:
        type: string
    account_id:
      name: "account_id"
      description: "The id for an account"
      in: path
      required: True
      schema:
        type: string
    account_id_query:
      name: "account_id_query"
      description: "The id for an account"
      in: query
      required: True
      schema:
        type: string

paths:
  /transactions:
    get:
      operationId: "transactions.read_all"
      tags:
        - "Transactions"
      summary: "Read the list of transactions"
      responses:
        "200":
          description: "Successfully read transaction list"
  /transactions/add:
    post:
      operationId: "transactions.add"
      tags:
        - "Transactions"
      summary: "Add transactions"
      requestBody:
          description: "Transactions to add"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "transaction"
                $ref: "#/components/schemas/Transaction"
      responses:
        "201":
          description: "Successfully added transaction"
  /transactions/clear:
    get:
      operationId: "transactions.clear"
      tags:
        - "Transactions"
      summary: "Clear all of the transactions in the database"
      responses:
        "200":
          description: "Successfully cleared all transactions from the database"
  /transactions/{id}:
    get:
      operationId: "transactions.read_one"
      tags:
        - "Transactions"
      summary: "Read one transaction"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Successfully read transaction"
    put:
      tags:
        - "Transactions"
      operationId: "transactions.update"
      summary: "Update a transaction"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Successfully updated transaction"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "transaction"
              $ref: "#/components/schemas/Transaction"
    delete:
      tags:
        - "Transactions"
      operationId: "transactions.delete"
      summary: "Delete a transaction"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          description: "Successfully deleted transaction"
  /transactions/search/{desc}:
    get:
      operationId: "transactions.search_desc"
      tags:
        - "Transactions"
      summary: "Search for description"
      parameters:
        - $ref: "#/components/parameters/desc"
      responses:
        "200":
          description: "Successfully returned matched descriptions"
  /upload:
    post:
      operationId: "upload.upload_file"
      tags:
        - "Upload"
      summary: "Upload csv"
      parameters:
        - $ref: "#/components/parameters/account_id_query"
      requestBody:
        description: .csv file 
        content:
          application/csv:
            schema:
              x-body-name: "file"
              type: string
              format: base64
      responses:
        "201":
          description: "Successfully uploaded"
  /accounts:
    get:
      operationId: "accounts.read_all"
      tags:
        - "Accounts"
      summary: "Get list of all accounts"
      responses:
        "200":
          description: "Successfully retrieved all accounts"
  /accounts/add:
    post:
      operationId: "accounts.add"
      tags:
        - "Accounts"
      summary: "Add account"
      requestBody:
          description: "Account to add"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "account"
                $ref: "#/components/schemas/Account"
      responses:
        "201":
          description: "Successfully added transaction"
  /accounts/{account_id}:
    get:
      operationId: "accounts.read_one"
      tags:
        - "Accounts"
      summary: "Read data about an account"
      parameters:
        - $ref: "#/components/parameters/account_id"
      responses:
        "200":
          description: "Successfully read account information"
  /accounts/clear:
    get:
      operationId: "accounts.clear"
      tags:
        - "Accounts"
      summary: "Clear all of the accounts in the database"
      responses:
        "200":
          description: "Successfully cleared all accounts from the database"
  /accounts/getTransactions:
    post:
      operationId: "accounts.getTransactions"
      tags:
        - "Accounts"
      summary: "Retrieve Transactions from account"
      requestBody:
          description: "Contain a list of accounts to retrieve transactions"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "account_list"
                type: array
      responses:
        "201":
          description: "Successfully retrieved transactions"
  /accounts/getSummary:
    get:
      operationId: "accounts.read_all_summary"
      tags:
        - "Accounts"
      summary: "Get summary list of all accounts"
      responses:
        "200":
          description: "Successfully retrieved all accounts"